[phases.setup]
nixPkgs = ["python311Full", "fonts-noto-color-emoji"]
aptPkgs = [
  "fonts-dejavu",
  "fonts-kacst",
  "fonts-kacst-one"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python professeur_agent_FINAL.py"
